"""Initial schema

Revision ID: 5bc9853382fd
Revises: 
Create Date: 2026-02-16 00:20:03.954921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc9853382fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('aws_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('aws_account_id', sa.String(length=12), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('role_arn', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'FAILED', name='integrationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_integrations_external_id'), 'aws_integrations', ['external_id'], unique=True)
    op.create_index(op.f('ix_aws_integrations_status'), 'aws_integrations', ['status'], unique=False)
    op.create_index(op.f('ix_aws_integrations_user_id'), 'aws_integrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aws_integrations_user_id'), table_name='aws_integrations')
    op.drop_index(op.f('ix_aws_integrations_status'), table_name='aws_integrations')
    op.drop_index(op.f('ix_aws_integrations_external_id'), table_name='aws_integrations')
    op.drop_table('aws_integrations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
